In [2]:
list1 = [1,2,3,4]
list2 = [2,3,4,5]

In [3]:
for i,j in zip(list1,list2):
    print(i+j)

3
5
7
9


In [5]:
list3 = []
for i,j in zip(list1,list2):
    list3.append(i+j)
print(list3)

[3, 5, 7, 9]


## Above Operation Using NumPy

In [7]:
# Import Numpy as np
import numpy as np

# Convert list1 and list2 to two different arrays
arr1 = np.array(list1)
arr2 = np.array(list2)
sum1 = arr1+arr2
sum1

array([3, 5, 7, 9])

In [8]:
# To check the list of variables, its type and other info
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        4
j          int        5
list1      list       n=4
list2      list       n=4
list3      list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


## Different Datatypes in Array

In [10]:
# list of List
data2 = [[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
arr3 = np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
# By default, the array is 2 dimensional
# To check the dimension of an array, use:
arr3.ndim

2

In [15]:
# To check the type of the array, use:
arr3.dtype

dtype('int32')

In [16]:
# To check the shape of the array, use: 
# Gives out (rows, column)
arr3.shape

(2, 4)

In [17]:
# To predefine the datatype
arr4 = np.array(data2, dtype=float)
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

## Range & Reshape Function

In [18]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [19]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
arr5 = np.arange(4,20)
arr5

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
arr6 = np.arange(4,20,2)
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Here arr6 has 1 row and 8 columns. To reshape it, use:
arr7 = arr6.reshape(4,2)
# Only condition : Product of rows and columns = Total number of elements
arr7

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [26]:
# To split a range into equal intervals, use:
arr8 = np.linspace(1,30,6)
arr8

array([ 1. ,  6.8, 12.6, 18.4, 24.2, 30. ])

## Operations using Index

In [90]:
ind = np.arange(5,21)
ind

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
# To select values indexed at 5 till the value 20, use:
ind[5:20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
# To use the value specified at a certain index, use:
ind[5]

10

In [30]:
# To use the values specified from one index till the end of the list, use:
ind[5:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
# To use the values specified from the beginning of the list till an index, use:
ind[:5]

array([5, 6, 7, 8, 9])

In [32]:
# To choose values indexed at multiple points, use list of list:
ind[[5,10,1]]

array([10, 15,  6])

## Arrays with multiple rows and negative numbers

In [33]:
ind1 = np.array([[-1,2,-3,4],[-5,6,7,-8],[9,-10,11,-12]])
ind1

array([[ -1,   2,  -3,   4],
       [ -5,   6,   7,  -8],
       [  9, -10,  11, -12]])

In [34]:
# to use a whole row, use its index value:
ind1[2]

array([  9, -10,  11, -12])

In [38]:
# to use a whole column, use:
ind1[:,2]

array([-3,  7, 11])

In [39]:
# to use a specific element in the arrays, use:
ind1[2,3]

-12

In [40]:
len(ind1)
# shows the number of elements in the array

3

In [41]:
len(ind)

16

In [43]:
ind

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
ind2=ind.reshape(4,4)
ind2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [46]:
ind2[:,[0,2]]
# prints the first and the third columns

array([[ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [49]:
ind2[:, 0:2]
# prints the first column and the column before thrid column

array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [54]:
ind2[:2,:]
# prints all rows till the second row(2nd not included), and all coulmns

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Sum of Elements

In [55]:
ind

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
ind.sum()
# Shows the sum of all elements in the array

200

In [57]:
np.sum(ind)
# Sum of elements using NumPy

200

In [58]:
# To find the mean/average of the elements in the array, use either:
ind.mean()
# or use:
np.mean(ind)

12.5

In [60]:
ind.median()
# There is no median function in Python

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [61]:
np.median(ind)
# Median function is available in NumPy

12.5

In [62]:
ind

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [92]:
ind=ind.reshape(4,4)
ind

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [67]:
ind.sum()

200

In [72]:
ind.sum(axis=1)
# Gives out the sum of elements along the x-axis, i.e., 5+6+7+8=26
# or
ind.sum(1)

array([26, 42, 58, 74])

In [74]:
ind.sum(axis=0)
# Gives out the sum of elements along the y-axis, i.e., 5+9+13+17=44
# or
ind.sum(0)

array([44, 48, 52, 56])

In [75]:
ind.reshape(1,16)

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

## Arthimetic Operations on Arrays

In [93]:
ind

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [77]:
# Scalar Addition
ind+5

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [78]:
# Scalar Subtraction
ind-5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
# Scalar Multiplication
(ind+5)*2

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50]])

In [81]:
# Scalar Division
((ind+5)*2)/4

array([[ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5]])

In [94]:
# Replacement of elements
ind[0]=-5
ind
#replaced the first row with -5

array([[-5, -5, -5, -5],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [96]:
# Absolute Function
ind=np.abs(ind)
ind

array([[ 5,  5,  5,  5],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [97]:
# Square Root of the elements
np.sqrt(ind)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894, 4.47213595]])

In [98]:
type(ind)
# Gives out the type of the array

numpy.ndarray

In [100]:
# To create an n*n array with ZERO as elements, use:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
# To create an n*n array with ONE as elements, use:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
# To create an IDENTITY matrix, use:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Dot Product & Transpose

In [105]:
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(4,2)
# Here, the number of columns in A = the number of rows in B
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [107]:
# Dot product of A and B
A.dot(B)

array([[28, 34],
       [76, 98]])

In [108]:
# Transpose of a matrix
A.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])